version: "3"

services:
  postgis:
    image: "mdillon/postgis:latest"
    volumes:
      - /volume/OneBitTinderApi/data/postgis:/var/lib/postgresql/data

  app:
    depends_on:
      - "postgis"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebittinder_api
      - gems:/gems


volumes:
  postgis:
  gems:
